### ISSUE TITLE
Add response header order

### ISSUE THREAD

**Issue by AlecHaring** [sleeyax/burp-awesome-tls#19]
If you compare the response header order of a request with and without the extension enabled, you'll notice it's different.

**`GET http://httpbin.org/get` with extension**:
<img width="849" alt="Screen Shot 2022-09-25 at 9 45 06 PM" src="https://user-images.githubusercontent.com/19616756/192178297-b408994c-64ad-450f-92d5-af3c3c679c74.png">

**`GET http://httpbin.org/get` without extension**:
<img width="853" alt="Screen Shot 2022-09-25 at 9 45 14 PM" src="https://user-images.githubusercontent.com/19616756/192178342-1e19fd6b-c047-41ef-b209-37c30c63bd80.png">

**Comment by AlecHaring** [comment]
`Header` stores the headers in a `map`, which doesn't preserve order. So we can't trust the order of `res.Header`, nor can we use the current method of transferring the response headers to the Burp response (`Header().Add`).

**Comment by sleeyax** [comment]
Thank you for opening a issue. Initially, I only aimed for the request headers to have the correct order because those can be prone to fingerprinting/censorship whereas response headers are only relevant for the developer/security researcher using Burp.

To support response headers order, I think you need to dig deeper into the `net/http` source code and find the code that writes the response header bytes into the header map. You can probably re-use the [HeaderOrderKey](https://github.com/sleeyax/burp-awesome-tls/blob/main/src-go/server/internal/net/http/header.go#L36) to store the order. 

I'd happily accept a PR for this.

**Comment by AlecHaring** [comment]
Yeah, I suspected that was the case. Definitely not as important as the request header order, as you said. It was just something I noticed, and I thought I should report it.

I noticed you have a copy of `net/http` in this repo with some patches. If needed, would you accept a PR that makes changes to that, or would you prefer a method that avoids changes to the `net/http` source?

**Comment by sleeyax** [comment]
> I noticed you have a copy of net/http in this repo with some patches. If needed, would you accept a PR that makes changes to that, or would you prefer a method that avoids changes to the net/http source?

If those changes are relevant to a feature/fix you are adding then sure, go ahead.

**Comment by sleeyax** [comment]
Marked as `wontfix` because I don't plan to work on this myself any time soon.
