### ISSUE TITLE
Requests being forced to use HTTP/1.1 protocol

### ISSUE THREAD

**Issue by AmmeySaini** [sleeyax/burp-awesome-tls#73]
I did notice a weird behavior whenever I load the extension all of the requests go through the HTTP/1.1 protocol. I've confirmed and checked this without the extension and the requests are on HTTP2

without extension:
![image](https://github.com/sleeyax/burp-awesome-tls/assets/65405363/389071d8-a22c-4950-8bb7-8e108dd98a27)

with extension:
![image](https://github.com/sleeyax/burp-awesome-tls/assets/65405363/c94c4927-7e14-4100-aa55-20a1f62933d1)

**Comment by sleeyax** [comment]
This is a limitation regarding the way Awesome TLS works (see [REAME.md#how-it-works](https://github.com/sleeyax/burp-awesome-tls?tab=readme-ov-file#how-it-works)). If you check the response from https://tls.peet.ws/api/all you can see it didn't *actually* send a HTTP 1 request, but a HTTP 2 request. It only *looks* that way in burp's request viewer because the [server part](https://github.com/sleeyax/burp-awesome-tls/tree/main/src-go/server) only supports HTTP 1. So it's more of a visual thing rather than an actual bug.

That being said, it's unfortunate that the used protocol information is lost. Maybe there's a way to improve this.

**Comment by AmmeySaini** [comment]
This is just for confirmation!!!
so what you are saying is that no request is going through HTTP1, it's just there for the request viewer??
There's a thing that I'm currently working on, the requests work fine on HTTP1, but I'm somehow being profiled while using HTTP2, so I just need to make sure that the requests are actually going through HTTP2 even if they show HTTP1 in the Burp

**Comment by sleeyax** [comment]
>  so what you are saying is that no request is going through HTTP1, it's just there for the request viewer??

Correct. 

There's currently no convenient way to confirm that HTTP 2 is used though, hence the new issue i created. I'll happily accept a PR for it if you're willing to give it a shot :)

**Comment by AmmeySaini** [comment]
I'll look into it. 
Thanks for the confirmation.
